apiVersion: v1
kind: Service
metadata:
  name: karantanwar-service
  labels:
    app: webapp 
spec:
  selector:
    app: webapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
